pipeline{

    agent any
    environment{

    }

    stages{
        stage('Preparando ambiente') {
            steps {
                echo 'Limpando a workspace'
            }
        }
        stage('Teste') {
            steps {
                echo 'Testando'
            }
        }
        stage('Build lint') {
            steps {
                echo 'Construindo Debug'
            }
        }
        stage('Build APK') {
            steps {
                echo 'Construindo APK'
            }
        }
    }
}